import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import { AppSidebar } from "@/components/app-sidebar";
import {
	SidebarInset,
	SidebarProvider,
	SidebarTrigger,
} from "@/components/ui/sidebar";
import { Button } from "@/components/ui/button";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<div className="flex h-dvh w-full">
					<SidebarProvider>
						<AppSidebar />
						<SidebarInset>
							<header className="relative flex h-16 shrink-0 items-center gap-2 border-b px-4">
								<div className="absolute top-4 left-4 z-50">
									<SidebarTrigger />
								</div>
							</header>
							<div className="h-full">{children}</div>
						</SidebarInset>
					</SidebarProvider>
				</div>
			</body>
		</html>
	);
}
