// lib/react-scaffold/templates.ts
export interface ReactScaffoldFile {
	path: string;
	content: string;
	language:
		| "json"
		| "javascript"
		| "typescript"
		| "jsx"
		| "tsx"
		| "css"
		| "html";
}

export interface ReactScaffoldTemplate {
	name: string;
	description: string;
	files: ReactScaffoldFile[];
	dependencies: string[];
	devDependencies: string[];
}

// Complete Vite React template with all features
export const completeReactTemplate: ReactScaffoldTemplate = {
	name: "complete-react",
	description:
		"Complete Vite React app with TypeScript, React Router, and Tailwind CSS",
	dependencies: ["react", "react-dom", "react-router-dom"],
	devDependencies: [
		"@types/react",
		"@types/react-dom",
		"@vitejs/plugin-react",
		"@tailwindcss/typography",
		"autoprefixer",
		"postcss",
		"tailwindcss",
		"typescript",
		"vite",
	],
	files: [
		{
			path: "package.json",
			content: JSON.stringify(
				{
					name: "react-app",
					private: true,
					version: "0.0.0",
					type: "module",
					scripts: {
						dev: "vite",
						build: "tsc && vite build",
						lint: "eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0",
						preview: "vite preview",
					},
					dependencies: {
						react: "^18.2.0",
						"react-dom": "^18.2.0",
						"react-router-dom": "^6.20.1",
					},
					devDependencies: {
						"@types/react": "^18.2.43",
						"@types/react-dom": "^18.2.17",
						"@typescript-eslint/eslint-plugin": "^6.14.0",
						"@typescript-eslint/parser": "^6.14.0",
						"@vitejs/plugin-react": "^4.2.1",
						"@tailwindcss/typography": "^0.5.10",
						autoprefixer: "^10.4.16",
						eslint: "^8.55.0",
						"eslint-plugin-react-hooks": "^4.6.0",
						"eslint-plugin-react-refresh": "^0.4.5",
						postcss: "^8.4.32",
						tailwindcss: "^3.3.6",
						typescript: "^5.2.2",
						vite: "^5.0.8",
					},
				},
				null,
				2,
			),
			language: "json",
		},
		{
			path: "index.html",
			content: `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>React App</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>`,
			language: "html",
		},
		{
			path: "src/main.tsx",
			content: `import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.tsx'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)`,
			language: "typescript",
		},
		// App.tsx will be generated by AI based on user requirements
		// This file is intentionally excluded from the template
		{
			path: "src/index.css",
			content: `@tailwind base;
@tailwind components;
@tailwind utilities;`,
			language: "css",
		},
		{
			path: "vite.config.ts",
			content: `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  server: {
    // Allow E2B sandbox hosts
    allowedHosts: [
      '.e2b.app'
    ],
    // Enable strict port and host checking
    strictPort: true,
    host: true
  }
})`,
			language: "typescript",
		},
		{
			path: "tsconfig.json",
			content: JSON.stringify(
				{
					compilerOptions: {
						target: "ES2020",
						useDefineForClassFields: true,
						lib: ["ES2020", "DOM", "DOM.Iterable"],
						module: "ESNext",
						skipLibCheck: true,
						moduleResolution: "bundler",
						allowImportingTsExtensions: true,
						resolveJsonModule: true,
						isolatedModules: true,
						noEmit: true,
						jsx: "react-jsx",
						strict: true,
						noUnusedLocals: true,
						noUnusedParameters: true,
						noFallthroughCasesInSwitch: true,
					},
					include: ["src"],
					references: [{ path: "./tsconfig.node.json" }],
				},
				null,
				2,
			),
			language: "json",
		},
		{
			path: "tsconfig.node.json",
			content: JSON.stringify(
				{
					compilerOptions: {
						compilerOptions: {
							composite: true,
							skipLibCheck: true,
							module: "ESNext",
							moduleResolution: "bundler",
							allowSyntheticDefaultImports: true,
							strict: true,
						},
						include: ["vite.config.ts"],
					},
				},
				null,
				2,
			),
			language: "json",
		},
		{
			path: "tailwind.config.js",
			content: `/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}`,
			language: "javascript",
		},
		{
			path: "postcss.config.js",
			content: `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}`,
			language: "javascript",
		},
	],
};

// Template array
export const allTemplates = [completeReactTemplate];

// Get template by name
export function getTemplate(name: string): ReactScaffoldTemplate | undefined {
	switch (name) {
		case "complete-react":
			return completeReactTemplate;
		default:
			return undefined;
	}
}

// Get all templates
export function getAllTemplates(): ReactScaffoldTemplate[] {
	return allTemplates;
}
